# Generated by Django 4.2.7 on 2025-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20),
        ),
    ]
