# Generated by Django 4.2.7 on 2025-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mp_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20),
        ),
    ]
