# Generated by Django 4.2.7 on 2025-11-12 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_costo_envio_order_latitud_order_longitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('orden', 'comprador', 'vendedor')},
        ),
    ]
