# Generated by Django 4.2.7 on 2025-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en domicilio del vendedor'), ('envio', 'Envío a domicilio')], default='retiro', max_length=20, verbose_name='Tipo de entrega'),
        ),
    ]
