# Generated by Django 4.2.7 on 2025-11-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_costo_envio_order_latitud_order_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('MP', 'Mercado Pago (Online)'), ('EF', 'Efectivo al Retirar')], default='MP', max_length=2, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('PAGO_PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pago Recibido'), ('ENVIADO', 'Enviado'), ('COMPLETADO', 'Completado y Entregado'), ('CANCELADO', 'Cancelado')], default='PAGO_PENDIENTE', max_length=20),
        ),
    ]
