# Generated by Django 4.2.7 on 2025-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_mp_preference_id_order_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
