# Generated by Django 4.2.7 on 2025-11-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='imagen',
            field=models.ImageField(upload_to='marketplace_images/'),
        ),
    ]
